### ISSUE TITLE
Validations not working for arrays search

### ISSUE THREAD

**Issue by stepanpelc** [sizek-cz/krv#4]
### krv version

0.1.1

### Kubernetes distribution and version

kind 1.27.3

### Deployed validation

```shell
apiVersion: krv.sizek.cz/v1
kind: Validation
metadata:
  name: example-array-etcd
spec:
  name: "etcd-kind-control-plane"
  namespace: "kube-system"
  resource: "Pod"
  validation:
    - jsonPath: "spec.containers[0].name"
      value: "etcd"
```

### Steps to reproduce

- Deploy validation

### Expected Behavior

OK state

### Actual Behavior

NOK state

**Comment by romanfurst** [comment]
intead of `spec.containers[0].name` it should be `spec.containers.0.name` . Example of usage added to documentation
